
import type { SVGProps } from 'react';
import {
  Crop,
  Scissors,
  GitMerge,
  RotateCcw,
  Gauge,
  Type,
  Sparkles,
  Clapperboard,
  Mic,
  Captions,
  SearchCode,
  Music2,
  Download,
  UploadCloud,
  Users,
  Image as ImageIcon,
  Play,
  Layers,
  Settings,
  Video,
  Volume2,
  Wand2,
  Save,
  Undo,
  Redo,
  FileVideo,
  Film,
  Palette,
  Github,
  Menu,
  X,
  PlusCircle,
  MinusCircle,
  ChevronsLeftRight,
  Eye,
  SlidersHorizontal,
  Share2,
  Trash2,
  LogIn,
  LogOut,
  UserCircle,
  Cloud,
  Moon,
  Sun,
  Monitor,
  LayoutGrid,
  List,
  Info,
  MoreVertical,
  HelpCircle,
  Bell,
  Folder,
  File,
  Star,
  Heart,
  Grid,
  Maximize,
  Minimize,
  ExternalLink,
  Link,
  Copy,
  Edit3,
  Loader2, // Added Loader2 for loading states
  LucideIcon
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  crop: Crop,
  scissors: Scissors,
  gitMerge: GitMerge,
  rotateCcw: RotateCcw,
  gauge: Gauge,
  type: Type,
  sparkles: Sparkles,
  clapperboard: Clapperboard,
  mic: Mic,
  captions: Captions,
  searchCode: SearchCode,
  music2: Music2,
  download: Download,
  uploadCloud: UploadCloud,
  users: Users,
  image: ImageIcon,
  play: Play,
  layers: Layers,
  settings: Settings,
  video: Video,
  volume2: Volume2,
  wand2: Wand2,
  save: Save,
  undo: Undo,
  redo: Redo,
  fileVideo: FileVideo,
  film: Film,
  palette: Palette,
  github: Github,
  menu: Menu,
  close: X,
  add: PlusCircle,
  remove: MinusCircle,
  panelToggle: ChevronsLeftRight,
  eye: Eye,
  sliders: SlidersHorizontal,
  share: Share2,
  trash: Trash2,
  login: LogIn,
  logout: LogOut,
  user: UserCircle,
  cloud: Cloud,
  moon: Moon,
  sun: Sun,
  system: Monitor,
  grid: LayoutGrid,
  list: List,
  info: Info,
  more: MoreVertical,
  help: HelpCircle,
  notifications: Bell,
  folder: Folder,
  file: File,
  star: Star,
  heart: Heart,
  layoutGrid: Grid,
  maximize: Maximize,
  minimize: Minimize,
  externalLink: ExternalLink,
  link: Link,
  copy: Copy,
  edit: Edit3,
  loader: Loader2, // Added Loader2
};

// Placeholder for app logo, you can replace this with an actual SVG
export const Logo = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
    <circle cx="12" cy="12" r="2" />
  </svg>
);
